### ISSUE TITLE
[CHECK] 모바일 웹 키보드

### ISSUE THREAD

**Issue by yoon-junseo** [dnd-side-project/dnd-5th-5-frontend#4]
## 설명
모바일 웹에서의 키보드 처리

## 확인사항
- [ ] 모바일에서 input에 foucs 하는 경우, 키보드에 따른 화면 이동 처리 가능한지

```
댓글로 레퍼런스 남기기
```

**Comment by yoon-junseo** [comment]
https://acat12.tistory.com/30

**Comment by 11t518s** [comment]
이거 그냥 테스트 삼에 아무 input 넣어놓고 모바일로 포커스 해봤는데 화면 이동 되는 듯?
